name: Deploy backend to main server

on:
  push:
    branches:
      - master
    paths:
      - backend/**
  workflow_dispatch:

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Run shell script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MAIN_SERVER_IP }}
          port: ${{ secrets.MAIN_SERVER_PORT }}
          username: ${{ secrets.MAIN_SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd ~/elice-project
            bash start.sh Backend-Sprint
