name: Deploy frontend to staging server

on:
  push:
    branches:
      - "Frontend-Sprint"

jobs:
  stage-frontend:
    name: Stage Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
        with:
          ref: Frontend-Sprint
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          check-latest: true
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Test and build
        run: npm run stage-build
      - name: Tar dist directory
        run: tar -cvf dist.tar dist
      - name: Deploy via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          port: ${{ secrets.STAGING_SERVER_PORT }}
          username: ${{ secrets.STAGING_SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "./frontend/dist.tar"
          target: "/var/www"
      - name: Run shell script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          port: ${{ secrets.STAGING_SERVER_PORT }}
          username: ${{ secrets.STAGING_SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd /var/www
            bash start.sh
